### PR TITLE
Always try to stop and remove any previously-created-container

### PR DESCRIPTION
**Pull request by fax4ever**
The event of having such containers defined is very unlikely, but it seems to be still possible.
See https://ci.hibernate.org/job/hibernate-search-performance/job/mapper-search5-elasticsearch/20/

### CODE REVIEW

**Comment by yrodiere** [comment]
If that's really possible, then please:

* use specific names for the containers, so that we can recognize them easily.
* add a single clean-up script, similar to [Quarkus's](https://github.com/quarkusio/quarkus/blob/e9d0186ae013a17a2a60ea5c339d180f9060684b/.github/docker-prune.sh#L14-L13), that you will execute wherever necessary. Quarkus executes it from the POM before integration tests, in particular: [see here](https://github.com/quarkusio/quarkus/blob/a3a47dcafdcde8da0c4f6c4c9f7c41e44ca49d8d/extensions/hibernate-search-orm-elasticsearch/deployment/pom.xml#L164-L179).

**Comment by yrodiere** [comment]
@fax4ever You forgot to check in the `docker-prune.sh` script. There's probably a gitignore rule that prevents that.

**Comment by fax4ever** [comment]
You're right. I did

**Comment by fax4ever** [comment]
Here is a performance test instance, using the current code base: https://ci.hibernate.org/job/hibernate-search-performance/job/fix-es-container-start-personal-fabio/5/console

**Comment by yrodiere** [comment]
Merged, thanks

**Pull request merged**
